EmailForm/Models/FormViewModel.cs
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace EmailForm.Models
{
  public class FormViewModel
    {
        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage ="Please enter valid email")]
        [JsonProperty("email")]
        public string Email { get; set; }
    }
}

EmailForm/Controllers/FormController.cs
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using EmailForm.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EmailForm.Controllers
{
    public class FormController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        private bool isResponseOk;

        public FormController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory ?? throw new ArgumentNullException(nameof(clientFactory));
        }

        [HttpGet]
        public ActionResult Submit()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Submit(FormViewModel form)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isSubmitted = await SubmitFormAsync(form);

                    if (isSubmitted)
                    {
                        return Ok();
                    }

                    return BadRequest();
                }

                return BadRequest();
            }
            catch
            {
                return BadRequest();
            }
        }

        private async Task<bool> SubmitFormAsync(FormViewModel form)
        {
            try
            {
                var url = $"https://us-central1-randomfails.cloudfunctions.net/submitEmail";
                var client = _clientFactory.CreateClient();
                var json = JsonConvert.SerializeObject(form);
                var content = new StringContent(json,
                                                Encoding.UTF8,
                                                "application/json");

                bool response = await SubmitFormRecursivelyAsync(url, client, content, 0);

                return response;
            }
            catch (Exception)
            {
                return false;
            }
        }

        private async Task<bool> SubmitFormRecursivelyAsync(string url, HttpClient client, StringContent content, int count)
        {
            //If there is a problem with connection to the external API the recursion has a guaranteed bottom.
            if (isResponseOk || count >= 1000)
            {
                return isResponseOk;
            }
            count++;
            var response = client.PostAsync(url, content);

            Action action = () => isResponseOk = isResponseOk == true ? true : response.Result.StatusCode == System.Net.HttpStatusCode.OK;

            response.GetAwaiter().OnCompleted(action);

            await SubmitFormRecursivelyAsync(url, client, content, count);

            return isResponseOk;
        }
    }
}

EmailForm/Views/Form/Submit.cshtml
@model EmailForm.Models.FormViewModel

@{
    ViewData["Title"] = "Submit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Please enter your email</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Submit" id="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" id="email" />
                <span asp-validation-for="Email" class="text-danger" id="emailValidation"></span>
            </div>
            <div class="form-group">
                <a onclick="submitForm(this)" class="btn btn-success" style="color:antiquewhite; cursor: pointer">Submit</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmailForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmailForm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/toastr.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Form" asp-action="Submit">EmailForm</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EmailForm
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/toastr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>